ARG BASE_IMAGE_VERSION=latest
ARG BASE_IMAGE=harbor.baai.ac.cn/flagbase/flagbase-nvidia
FROM ${BASE_IMAGE}:${BASE_IMAGE_VERSION}
# 
ARG VENDOR=USE_NVIDIA
# workdir
WORKDIR /workspace
COPY . /workspace/SDCCL
WORKDIR /workspace/SDCCL

# build
RUN make ${VENDOR}=1
