repos:
-   repo: local
    hooks:
      - id: clang-format-dry-run
        name: clang-format-dry-run
        entry: clang-format --dry-run --Werror
        files: \.(cpp|cc|h|hpp)$
        language: system

-   repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format -i --style=file
        files: \.(cpp|cc|h|hpp)$
        language: system

# -   repo: local
#     hooks:
#       - id: clang-tidy
#         name: clang-tidy
#         entry: clang-tidy --config-file=.clang-tidy
#         files: \.(cpp|cc|h|hpp)$
#         # skip for the moment 
#         exclude: |
#           (?x)^(
#               sdccl/sdccl.cc|
#               sdccl/include/sdccl.h
#           )$
#         language: system
