#!/bin/bash
# example multi-node script generated by run_torch_test.py
set -euo pipefail
source /root/miniconda3/bin/activate flagscale-train

export SDCCL_DEBUG=INFO
export SDCCL_DEBUG_SUBSYS=ALL
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7

torchrun --nnodes 2 --nproc_per_node 8 --node_rank 0 --master_addr 1.1.1.1 --master_port 8281 ../example.py
