BUILDDIR ?= $(abspath ./build)

BINDIR := $(BUILDDIR)/bin
OBJDIR := $(BUILDDIR)/obj




INCLUDEDIR := \
        $(abspath include) \
        $(abspath coll/include) \
        $(abspath kernel/include) \
        $(abspath topo/include) \
        $(abspath ../../third-party/googletest/googletest/include)

LIBSRCFILES := \
        $(wildcard *.cpp) \
        $(wildcard coll/*.cpp) \
        $(wildcard kernel/*.cpp) \
        $(wildcard topo/*.cpp)

BINOBJ := $(LIBSRCFILES:%.cpp=$(OBJDIR)/%.o)




GTEST_DIR := ../../third-party/googletest
GTEST_LIB := $(GTEST_DIR)/build/lib


MPI_HOME ?= /usr/local/mpi
MPI_INCLUDE = $(MPI_HOME)/include
MPI_LIB = $(MPI_HOME)/lib


TARGET = main
all: $(BINDIR)/$(TARGET)

$(BINDIR)/$(TARGET): $(BINOBJ)
	@mkdir -p `dirname $@`
	@echo "Linking   $@"
	@g++ $(BINOBJ) -o $@ -L../../build/lib -L$(MPI_LIB) -L/usr/local/lib -L$(GTEST_LIB) -Wl,--no-as-needed -Wl,-rpath,../../build/lib -lsdccl -lmpi -lgtest -lgtest_main -lpthread -g

$(OBJDIR)/%.o: %.cpp
	@mkdir -p `dirname $@`
	@echo "Compiling $@"
	@g++ $< -o $@ $(foreach dir,$(INCLUDEDIR),-I$(dir)) -I../../sdccl/include -I../../sdccl/adaptor/include -I../../sdccl/service/include -I../../sdccl/core/include -I../../third-party/json/single_include -I$(MPI_INCLUDE) -I/usr/local/include -c -Wvla -Wno-unused-function -Wno-sign-compare -Wall -g

-include $(BINOBJ:.o=.d)

clean:
	@rm -rf $(BINDIR)/$(TARGET) $(OBJDIR)

run-all-tests:
	@mpirun --allow-run-as-root -np 8 -x UCX_POSIX_USE_PROC_LINK=n -x CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 -x SDCCL_LOG_LEVEL=TRACE -x SDCCL_TOPO_FILE="topo_demo.xml" -x SDCCL_DEBUG=TRACE -x SDCCL_DEBUG_SUBSYS=ALL ./build/bin/main
