name: Sync to remote site
on:

  workflow_dispatch:

  # Note: use 'push' because we want to cover both manual push
  # and PR merge events.
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  sync:
    strategy:
      matrix:
        include:
          - job_name: sync-to-gitcode
            remote: gitcode.com
            repository: SDCCL
            branch: master
          - job_name: sync-to-gitlink
            remote: code.gitlink.org.cn
            repository: SDCCL
            branch: master
    name: ${{ matrix.job_name }}
    uses: flagos-ai/build-infra/.github/workflows/sync-to-remote.yaml@main
    with:
      remote: ${{ matrix.remote }}
      repository: ${{ matrix.repository }}
      branch: ${{ matrix.branch }}
    secrets:
      GITCODE_SSH_KEY: ${{ secrets.GITCODE_SSH_KEY }}
