name: Docker Image Build Orchestrator

on:
  schedule:
    - cron: '0 2 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      push_images:
        description: 'push image or not'
        type: boolean
        default: false

jobs:
  build-matrix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - job_name: buildcx-nvidia-image
            push: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            containerfile: 'containerfile'
            image_name: 'sdccl-nvidia'
            tag: 'latest'
            runson: 'h20'
            no-cache: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            build-args: |
              BASE_IMAGE=harbor.baai.ac.cn/flagbase/flagbase-nvidia
              BASE_IMAGE_VERSION=latest
              VENDOR=USE_NVIDIA
          
          # use h20 instance just for build image.
          - job_name: buildcx-metax-image
            push: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            containerfile: 'containerfile'
            image_name: 'sdccl-metax'
            tag: 'latest'
            runson: 'h20'
            no-cache: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            build-args: |
              BASE_IMAGE=harbor.baai.ac.cn/flagbase/flagbase-metax
              BASE_IMAGE_VERSION=latest
              VENDOR=USE_METAX

          # use h20 instance just for build image.
          - job_name: buildcx-ascend-image
            push: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            containerfile: 'containerfile'
            image_name: 'sdccl-ascend'
            tag: 'latest'
            runson: 'h20'
            no-cache: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            build-args: |
              BASE_IMAGE=harbor.baai.ac.cn/flagbase/flagbase-ascend
              BASE_IMAGE_VERSION=latest
              VENDOR=USE_ASCEND

          # use h20 instance just for build image.
          - job_name: buildcx-tsingmicro-image
            push: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            containerfile: 'containerfile'
            image_name: 'sdccl-tsingmicro'
            tag: 'latest'
            runson: 'h20'
            no-cache: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            build-args: |
              BASE_IMAGE=harbor.baai.ac.cn/flagbase/flagbase-tsingmicro
              BASE_IMAGE_VERSION=latest
              VENDOR=USE_TSM
    
    uses: flagos-ai/build-infra/.github/workflows/imagebuild.yml@main
    with:
      push: ${{ matrix.push }}
      containerfile: ${{ matrix.containerfile }}
      image_name: ${{ matrix.image_name }}
      tag: ${{ matrix.tag }}
      runson: ${{ matrix.runson }}
      build-args: ${{ matrix.build-args }}
      image_prefix: 'sdccl'
      no-cache: ${{ matrix.no-cache }}
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      RUNNER_SSH_KEY: ${{ secrets.RUNNER_SSH_KEY }}
